### ISSUE TITLE
Bootloop - Android 9.0 - Pixel XL - Flash Kernel 2.06

### ISSUE THREAD

**Issue by Jezza-x3** [Magisk-Modules-Repo/Greenify4Magisk#6]
I think since it's not signed and is being installed in /system that it's breaking the boot.

**Comment by soraxas** [comment]
Can confirm, I have the same device with Android Pie, it will enters bootloop with this module installed

**Comment by waysup** [comment]
@darren3 pixel 2 and 2xl bootloop too:grinning:

**Comment by DevBonBon** [comment]
(Before posting I noticed this in the Unity installer thread: "ROOT - Location of root of file system such as with pixels using supersu (where instead of being nothing, is /system_root)" I have no idea how pixel devices work, but could it be possible that the apk is not going where it's supposed to go?)

One idea would be to try and move an existing Greenify apk (from data/app) into /system on boot. This would also make the module smaller, as it doesn't have to include the apk anymore.
I'm trying to make this happen, but my bash skills are extremely rusty, so it'll probably take a long time, if I ever even manage to finish it.

**Comment by DevBonBon** [comment]
Ok, i now know how to do this, but would it actually be a wanted feature? It would make the module smaller, but also increase maintainability. I'd be happy to make the original implementation, but won't probably stick around to maintain it, so if it's not something you actually want, i won't make the pull request.

**Comment by Abacate123** [comment]
> @Abacate123 Ok, i now know how to do this, but would it actually be a wanted feature? It would make the module smaller, but also increase maintainability. I'd be happy to make the original implementation, but won't probably stick around to maintain it, so if it's not something you actually want, i won't make the pull request.

Well, we can try this, sure, and see how this goes. I can (or even you, since you're the one trying to fix) post this modified zip in my thread and ask for users feedback. In case there are no issues, I could make both versions available for download. Let's see.
